[doot]
name = "Hyprland"
authors = ["Main Menu <corigan01@gmail.com>"]
topic = "My clasic FreeBSD Hyprland config with wallpaper"
version = "0.2.0"

[config]
target = ["~/.config/hypr/hyprland.conf", "~/.config/hypr/hyprpaper.conf"]
source = ["./hypr/hyprland.conf", "./hypr/hyprpaper.conf"]
ask = true
debug = true
